-- Add default values to nullable fields that are causing the registration error
ALTER TABLE users MODIFY COLUMN openId VARCHAR(64) UNIQUE DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN googleId VARCHAR(255) UNIQUE DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN accountStatusReason TEXT DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN mfaSecret VARCHAR(255) DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN mfaBackupCodes TEXT DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN lastFailedLoginAt TIMESTAMP DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN accountLockedUntil TIMESTAMP DEFAULT NULL;

-- Make required fields NOT NULL
ALTER TABLE users MODIFY COLUMN name TEXT NOT NULL;
ALTER TABLE users MODIFY COLUMN email VARCHAR(320) NOT NULL;
ALTER TABLE users MODIFY COLUMN loginMethod VARCHAR(64) NOT NULL;
