CREATE TABLE `vetReviewStats` (
	`id` int AUTO_INCREMENT NOT NULL,
	`veterinarianId` int NOT NULL,
	`totalReviews` int DEFAULT 0,
	`averageRating` decimal(3,2) DEFAULT '0.00',
	`averageProfessionalism` decimal(3,2) DEFAULT '0.00',
	`averageCommunication` decimal(3,2) DEFAULT '0.00',
	`averagePriceValue` decimal(3,2) DEFAULT '0.00',
	`averageTreatmentEffectiveness` decimal(3,2) DEFAULT '0.00',
	`recommendationPercentage` int DEFAULT 0,
	`fiveStarCount` int DEFAULT 0,
	`fourStarCount` int DEFAULT 0,
	`threeStarCount` int DEFAULT 0,
	`twoStarCount` int DEFAULT 0,
	`oneStarCount` int DEFAULT 0,
	`lastUpdated` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `vetReviewStats_id` PRIMARY KEY(`id`),
	CONSTRAINT `vetReviewStats_veterinarianId_unique` UNIQUE(`veterinarianId`)
);
--> statement-breakpoint
CREATE TABLE `vetReviews` (
	`id` int AUTO_INCREMENT NOT NULL,
	`veterinarianId` int NOT NULL,
	`farmId` int NOT NULL,
	`userId` int NOT NULL,
	`appointmentId` int,
	`rating` int NOT NULL,
	`reviewTitle` varchar(255) NOT NULL,
	`reviewText` text,
	`professionalismRating` int,
	`communicationRating` int,
	`priceValueRating` int,
	`treatmentEffectivenessRating` int,
	`animalSpecies` varchar(100),
	`treatmentType` varchar(255),
	`wouldRecommend` boolean DEFAULT true,
	`helpfulCount` int DEFAULT 0,
	`unhelpfulCount` int DEFAULT 0,
	`isVerified` boolean DEFAULT false,
	`isAnonymous` boolean DEFAULT false,
	`status` enum('pending','approved','rejected','hidden') DEFAULT 'pending',
	`moderationNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vetReviews_id` PRIMARY KEY(`id`)
);
