CREATE TABLE `fieldHealthRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`recordId` varchar(64) NOT NULL,
	`segmentId` int NOT NULL,
	`farmId` int NOT NULL,
	`recordDate` date NOT NULL,
	`healthScore` decimal(5,2),
	`diseasePresence` varchar(255),
	`pestPresence` varchar(255),
	`weedDensity` varchar(50),
	`cropCondition` enum('excellent','good','fair','poor','critical') DEFAULT 'good',
	`irrigationStatus` varchar(100),
	`nutrientDeficiency` varchar(255),
	`photoUrl` varchar(500),
	`notes` text,
	`recordedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fieldHealthRecords_id` PRIMARY KEY(`id`),
	CONSTRAINT `fieldHealthRecords_recordId_unique` UNIQUE(`recordId`)
);
--> statement-breakpoint
CREATE TABLE `fieldManagementPlans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`planId` varchar(64) NOT NULL,
	`segmentId` int NOT NULL,
	`fieldId` int NOT NULL,
	`farmId` int NOT NULL,
	`planName` varchar(255) NOT NULL,
	`description` text,
	`planType` enum('crop_rotation','soil_improvement','pest_management','irrigation','fertilization') NOT NULL,
	`startDate` date NOT NULL,
	`endDate` date,
	`objectives` text,
	`activities` text,
	`budget` decimal(15,2),
	`status` enum('draft','active','completed','cancelled') DEFAULT 'draft',
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fieldManagementPlans_id` PRIMARY KEY(`id`),
	CONSTRAINT `fieldManagementPlans_planId_unique` UNIQUE(`planId`)
);
--> statement-breakpoint
CREATE TABLE `fieldSegmentTasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`taskId` varchar(64) NOT NULL,
	`segmentId` int NOT NULL,
	`farmId` int NOT NULL,
	`taskType` varchar(100) NOT NULL,
	`taskName` varchar(255) NOT NULL,
	`description` text,
	`priority` enum('low','medium','high','urgent') DEFAULT 'medium',
	`status` enum('pending','in_progress','completed','cancelled','on_hold') DEFAULT 'pending',
	`assignedWorkerId` int,
	`estimatedHours` decimal(10,2),
	`actualHours` decimal(10,2),
	`scheduledDate` date,
	`completionDate` date,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fieldSegmentTasks_id` PRIMARY KEY(`id`),
	CONSTRAINT `fieldSegmentTasks_taskId_unique` UNIQUE(`taskId`)
);
--> statement-breakpoint
CREATE TABLE `fieldSegments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`segmentId` varchar(64) NOT NULL,
	`fieldId` int NOT NULL,
	`farmId` int NOT NULL,
	`segmentName` varchar(255) NOT NULL,
	`segmentCode` varchar(50) NOT NULL,
	`description` text,
	`areaHectares` decimal(10,2) NOT NULL,
	`gpsLatitude` decimal(10,8),
	`gpsLongitude` decimal(11,8),
	`segmentationType` enum('geographic','soil_type','irrigation','crop_variety','management_zone') DEFAULT 'geographic',
	`soilType` varchar(100),
	`soilPH` decimal(3,1),
	`moistureLevel` decimal(5,2),
	`nitrogenLevel` decimal(5,2),
	`phosphorusLevel` decimal(5,2),
	`potassiumLevel` decimal(5,2),
	`segmentStatus` enum('active','inactive','treatment','monitoring') DEFAULT 'active',
	`riskLevel` enum('low','medium','high','critical') DEFAULT 'low',
	`lastAssessmentDate` date,
	`nextAssessmentDate` date,
	`photoUrl` varchar(500),
	`metadata` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fieldSegments_id` PRIMARY KEY(`id`),
	CONSTRAINT `fieldSegments_segmentId_unique` UNIQUE(`segmentId`)
);
--> statement-breakpoint
CREATE TABLE `fieldYieldRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`yieldId` varchar(64) NOT NULL,
	`segmentId` int NOT NULL,
	`fieldId` int NOT NULL,
	`farmId` int NOT NULL,
	`harvestDate` date NOT NULL,
	`cropId` int NOT NULL,
	`cropCycleId` int,
	`quantityHarvested` decimal(10,2) NOT NULL,
	`unit` varchar(50) DEFAULT 'kg',
	`yieldPerHectare` decimal(10,2),
	`quality` enum('premium','grade_a','grade_b','grade_c','rejected') DEFAULT 'grade_a',
	`marketPrice` decimal(10,2),
	`totalValue` decimal(15,2),
	`notes` text,
	`recordedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fieldYieldRecords_id` PRIMARY KEY(`id`),
	CONSTRAINT `fieldYieldRecords_yieldId_unique` UNIQUE(`yieldId`)
);
--> statement-breakpoint
CREATE TABLE `fields` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fieldId` varchar(64) NOT NULL,
	`farmId` int NOT NULL,
	`fieldName` varchar(255) NOT NULL,
	`fieldCode` varchar(50) NOT NULL,
	`description` text,
	`areaHectares` decimal(10,2) NOT NULL,
	`gpsLatitude` decimal(10,8),
	`gpsLongitude` decimal(11,8),
	`soilType` varchar(100),
	`soilPH` decimal(3,1),
	`waterSource` varchar(100),
	`fieldStatus` enum('active','fallow','preparation','harvested','archived') DEFAULT 'active',
	`cropId` int,
	`currentCropCycleId` int,
	`lastHarvestDate` date,
	`nextPlantingDate` date,
	`photoUrl` varchar(500),
	`metadata` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fields_id` PRIMARY KEY(`id`),
	CONSTRAINT `fields_fieldId_unique` UNIQUE(`fieldId`)
);
